[[plugins]]
 repo = 'vim-denops/denops.vim'
[[plugins]]
 repo = 'cohama/lexima.vim'
[[plugins]]
 repo = 'pepo-le/win.ime-con.nvim'
[[plugins]]
 repo = 'markonm/traces.vim'
[[plugins]]
 repo = 'Shougo/defx.nvim'
[[plugins]]
 repo = 'kannokanno/previm'
 [[plugins]]
repo = 'mattn/vim-maketable'
[[plugins]]
repo = 'skanehira/translate.vim'
# スクロール
[[plugins]]
repo = 'yuttie/comfortable-motion.vim'
# 行末の空白
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'